# Generated by Django 5.1.3 on 2024-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test01',
            fields=[
                ('memo_id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='memo_id')),
                ('memo_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='memo_title')),
                ('contents', models.TextField(blank=True, max_length=516, null=True, verbose_name='contents')),
                ('register_dttm', models.DateTimeField(auto_now=True, max_length=14, verbose_name='registered_datetime')),
                ('lastupdate_dttm', models.DateTimeField(auto_now_add=True, max_length=14, verbose_name='lastupdate_datetime')),
            ],
            options={
                'verbose_name_plural': 't_memo',
                'db_table': 't_memo',
            },
        ),
    ]
